In [25]:
# Standard imports
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
from sklearn import datasets

# Load the mushroom data
mushroom_data = pd.read_csv("agaricus-lepiota.csv", header=0)

dataframe = mushroom_data.drop(["edibility"], 1)
X = pd.get_dummies(dataframe).values
header = pd.get_dummies(dataframe).columns.values

edibility = {
    'e' : 1,
    'p' : 0
}
y_list = []

print(X)
for i, row in mushroom_data.iterrows():
    y_list.append(edibility[row['edibility']])
    
y = np.array(y_list)

print(y)

skb = SelectKBest(chi2, k=3)
skb.fit(X, y)
X_new = skb.transform(X)

np.array(header)[skb.get_support(indices=True)]

[[0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[0 1 1 ... 1 0 1]


array(['odor_f', 'odor_n', 'stalk-surface-above-ring_k'], dtype=object)